#!/bin/sh

if [ purge = "$1" ]; then
        update-rc.d avocadodb3 remove >/dev/null

	rm -rf /usr/share/avocadodb3/js/apps
	rm -rf /var/log/avocadodb3
	rm -rf /var/lib/avocadodb3
	rm -rf /var/lib/avocadodb3-apps 
fi
