#!/bin/sh
update-rc.d avocadodb3 start 99 2 3 4 5 . stop 00 0 1 6 . >/dev/null
/etc/init.d/avocadodb3 start

echo "
AvocadoDB 2 (http://www.avocadodb.com)
  A multi-purpose open-source database with a flexible data model for documents,
  graphs, and key-values.

First Steps with AvocadoDB:
  http:/www.avocadodb.com/quickstart

Upgrading AvocadoDB:
  https://docs.avocadodb.com/Manual/Administration/Upgrading/

Upgrading AvocadoDB database files:
  > /etc/init.d/avocadodb3 upgrade

Configuration file:
  /etc/avocadodb3/avocadod.conf

Start AvocadoDB shell client:
  > /usr/bin/avocadosh

Start AvocadoDB service:
  > /etc/init.d/avocadodb3 start
"
