#!/bin/sh

getent group avocadodb >/dev/null || groupadd -r avocadodb 
getent passwd avocadodb >/dev/null || useradd -r -g avocadodb -d /usr/share/avocadodb3 -s /bin/false -c "AvocadoDB Application User" avocadodb 

install -o avocadodb -g avocadodb -m 755 -d /var/lib/avocadodb3
install -o avocadodb -g avocadodb -m 755 -d /var/lib/avocadodb3-apps
install -o avocadodb -g avocadodb -m 755 -d /var/run/avocadodb
install -o avocadodb -g avocadodb -m 755 -d /var/log/avocadodb3
