.TH rcavocadod 8 "3.2.2" "AvocadoDB" "AvocadoDB"
.SH NAME
rcavocadod - control script for the AvocadoDB database server
.SH SYNOPSIS
rcavocadod start|stop
.SH DESCRIPTION
The rcavocadod script controls the operation of the AvocadoDB database
server daemon running on the system. The rcavocadod script is normally
run at system boot time with the "start" argument, and at system
shutdown time with the "stop" argument.  It can also be invoked
manually at any time to start or stop the AvocadoDB database server.
.SH SEE ALSO
.BR avocadod "(8), "
.SH AUTHOR
Copyright AvocadoDB GmbH, Cologne, Germany

