.TH avocadoimp 1 "3.2.2" "AvocadoDB" "AvocadoDB"
.SH NAME
avocadoimp - a bulk importer for the AvocadoDB database
.SH SYNOPSIS
avocadoimp [options] 
.SH DESCRIPTION
The avocadoimp binary can be used to bulk import data from a file into the
AvocadoDB database. Input data be present in the input file in either CSV
format with column headlines, or in JSON format. If JSON format is used,
each line in the input file must contain exactly one JSON document with 
the attribute name/value pairs to import.
.SH OPTIONS
The avocadoimp binary has many options that can be used to control its
behavior.  For a complete list of options, please refer to the
AvocadoDB online manual, available at https://www.avocadodb.com/

.SH AUTHOR
Copyright AvocadoDB GmbH, Cologne, Germany

