.TH avocadosh 1 "3.2.2" "AvocadoDB" "AvocadoDB"
.SH NAME
avocadosh - the AvocadoDB shell
.SH SYNOPSIS
avocadosh [options]
.SH DESCRIPTION
The avocadosh binary can be used to establish an interactive
client connection to the AvocadoDB database. When the connection
is established, it can be used to execute actions on the server.
.SH OPTIONS
For a complete list of options, please refer to the AvocadoDB
online manual, available at https://www.avocadodb.com/

.SH AUTHOR
Copyright AvocadoDB GmbH, Cologne, Germany

