.TH avocadobench 1 "3.2.2" "AvocadoDB" "AvocadoDB"
.SH NAME
avocadobench - the AvocadoDB benchmark and test tool
.SH SYNOPSIS
avocadobench [options]
.SH DESCRIPTION
The avocadob binary can be used to issue test requests to the 
AvocadoDB database. It can be used for benchmarks or server function
testing. It supports parallel querying and batch requests.
.SH OPTIONS
For a complete list of options, please refer to the AvocadoDB
online manual, available at https://www.avocadodb.com/

.SH AUTHOR
Copyright AvocadoDB GmbH, Cologne, Germany

